// app/Utils/dummyData.ts
import { IBlogItems } from "./Interfaces";

export const dummyBlogData: IBlogItems[] = [
  {
    id: 1,
    userId: 0,
    publisherName: "DemoChef",
    date: new Date().toISOString(),
    image: "/assets/DummyData/pancakes.png",
    recipeName: "Demo Pancakes",
    description: "Fluffy demo pancakes made with love.",
    ingredients: [
      {
        title: "Main Ingredients",
        ingredients: ["1 cup flour", "2 eggs", "1 cup milk", "1 tbsp sugar"],
      },
    ],
    steps: [
      {
        title: "Instructions",
        steps: ["Mix ingredients", "Pour in pan", "Flip", "Serve hot"],
      },
    ],
    tags: ["demo", "easy", "breakfast"],
    rating: 0,
    numberOfRatings: 0,
    averageRating: 0,
    numberOfLikes: 0,
    postType: "recipe",
    totalTime: "15 min",
    servings: "2",
    source: "Demo Source",
    isPublished: true,
    isDeleted: false,
  },
  {
    id: 2,
    userId: 1,
    publisherName: "FoodieGal",
    date: new Date().toISOString(),
    image: "/assets/DummyData/buddhabowl.png",
    recipeName: "Healthy Buddha Bowl",
    description: "A colorful bowl of fresh veggies and grains.",
    ingredients: [
      {
        title: "What You Need",
        ingredients: ["Quinoa", "Chickpeas", "Spinach", "Avocado", "Carrots"],
      },
    ],
    steps: [
      {
        title: "Prep",
        steps: ["Cook quinoa", "Roast chickpeas", "Assemble everything in bowl"],
      },
    ],
    tags: ["healthy", "vegan", "lunch"],
    rating: 0,
    numberOfRatings: 0,
    averageRating: 0,
    numberOfLikes: 0,
    postType: "recipe",
    totalTime: "20 min",
    servings: "1",
    source: "Foodie Gal's Blog",
    isPublished: true,
    isDeleted: false,
  },
  {
    id: 3,
    userId: 2,
    publisherName: "ChefSnap",
    date: new Date().toISOString(),
    image: "/assets/DummyData/summersalad.png",
    recipeName: "Summer Salad Vibes",
    description: "Fresh salad image to inspire your next meal.",
    ingredients: [],
    steps: [],
    tags: ["image", "salad", "inspo"],
    rating: 0,
    numberOfRatings: 0,
    averageRating: 0,
    numberOfLikes: 0,
    postType: "image",
    totalTime: "",
    servings: "",
    source: "",
    isPublished: true,
    isDeleted: false,
  },
  {
    id: 4,
    userId: 3,
    publisherName: "QuickFix",
    date: new Date().toISOString(),
    image: "/assets/DummyData/berrysmoothie.png",
    recipeName: "Berry Smoothie Boost",
    description: "Quick and energizing berry smoothie recipe.",
    ingredients: [
      {
        title: "Blend This",
        ingredients: ["1 banana", "1 cup berries", "1/2 cup yogurt", "Honey"],
      },
    ],
    steps: [
      {
        title: "How To Make",
        steps: ["Put everything in blender", "Blend till smooth", "Serve cold"],
      },
    ],
    tags: ["smoothie", "fast", "energy"],
    rating: 0,
    numberOfRatings: 0,
    averageRating: 0,
    numberOfLikes: 0,
    postType: "recipe",
    totalTime: "5 min",
    servings: "1",
    source: "QuickFix Recipes",
    isPublished: true,
    isDeleted: false,
  },
  {
    id: 5,
    userId: 4,
    publisherName: "SnackShots",
    date: new Date().toISOString(),
    image: "/assets/DummyData/chips.png",
    recipeName: "Snack Time!",
    description: "Photo drop: tortilla chips and spicy guac.",
    ingredients: [],
    steps: [],
    tags: ["snack", "photo", "chips"],
    rating: 0,
    numberOfRatings: 0,
    averageRating: 0,
    numberOfLikes: 0,
    postType: "image",
    totalTime: "",
    servings: "",
    source: "",
    isPublished: true,
    isDeleted: false,
  },
  {
    id: 6,
    userId: 5,
    publisherName: "LazyCook",
    date: new Date().toISOString(),
    image: "/assets/DummyData/eggsontoast.png",
    recipeName: "Eggs on Toast",
    description: "A quick classic breakfast recipe.",
    ingredients: [
      {
        title: "Ingredients",
        ingredients: ["2 eggs", "2 slices bread", "Salt", "Pepper", "Butter"],
      },
    ],
    steps: [
      {
        title: "Steps",
        steps: ["Toast bread", "Fry eggs", "Assemble and season"],
      },
    ],
    tags: ["easy", "breakfast", "classic"],
    rating: 0,
    numberOfRatings: 0,
    averageRating: 0,
    numberOfLikes: 0,
    postType: "recipe",
    totalTime: "10 min",
    servings: "1",
    source: "LazyCook",
    isPublished: true,
    isDeleted: false,
  },
  {
  id: 7,
  userId: 6,
  publisherName: "GlobalGrub",
  date: new Date().toISOString(),
  image: "/assets/DummyData/tikka.png",
  recipeName: "Chicken Tikka Skewers",
  description: "Flavorful Indian-style skewers perfect for grilling.",
  ingredients: [
    {
      title: "Marinade",
      ingredients: [
        "500g chicken breast",
        "1/2 cup yogurt",
        "1 tbsp garam masala",
        "1 tsp turmeric",
        "Salt",
        "Lemon juice"
      ],
    },
  ],
  steps: [
    {
      title: "Cooking Instructions",
      steps: [
        "Marinate chicken for 2 hours",
        "Skewer and grill on medium heat",
        "Serve with chutney"
      ],
    },
  ],
  tags: ["indian", "grill", "spicy"],
  rating: 0,
  numberOfRatings: 0,
  averageRating: 0,
  numberOfLikes: 0,
  postType: "recipe",
  totalTime: "2 hr 20 min (with marination)",
  servings: "4",
  source: "Global Grub",
  isPublished: true,
  isDeleted: false,
},
{
  id: 8,
  userId: 7,
  publisherName: "VeggieVibes",
  date: new Date().toISOString(),
  image: "/assets/DummyData/stirfry.png",
  recipeName: "Rainbow Veggie Stir-Fry",
  description: "A quick and colorful vegan stir-fry.",
  ingredients: [
    {
      title: "Ingredients",
      ingredients: [
        "Bell peppers (3 colors)",
        "1 zucchini",
        "1 red onion",
        "Soy sauce",
        "Garlic",
        "Olive oil"
      ],
    },
  ],
  steps: [
    {
      title: "Instructions",
      steps: [
        "Chop all veggies",
        "Stir-fry in pan with oil and garlic",
        "Add soy sauce to taste"
      ],
    },
  ],
  tags: ["vegan", "quick", "dinner"],
  rating: 0,
  numberOfRatings: 0,
  averageRating: 0,
  numberOfLikes: 0,
  postType: "recipe",
  totalTime: "15 min",
  servings: "2",
  source: "Veggie Vibes",
  isPublished: true,
  isDeleted: false,
},
{
  id: 9,
  userId: 8,
  publisherName: "SweetCrumbs",
  date: new Date().toISOString(),
  image: "/assets/DummyData/cookies.png",
  recipeName: "Chocolate Chip Cookies",
  description: "Soft and chewy cookies with gooey chocolate.",
  ingredients: [
    {
      title: "What You'll Need",
      ingredients: [
        "2 cups flour",
        "1 cup sugar",
        "1/2 cup butter",
        "2 eggs",
        "1 tsp vanilla",
        "1 cup chocolate chips"
      ],
    },
  ],
  steps: [
    {
      title: "Bake Like This",
      steps: [
        "Preheat oven to 350°F",
        "Mix ingredients",
        "Scoop onto tray",
        "Bake for 12 minutes"
      ],
    },
  ],
  tags: ["dessert", "cookies", "baking"],
  rating: 0,
  numberOfRatings: 0,
  averageRating: 0,
  numberOfLikes: 0,
  postType: "recipe",
  totalTime: "25 min",
  servings: "12 cookies",
  source: "Sweet Crumbs",
  isPublished: true,
  isDeleted: false,
},
{
  id: 10,
  userId: 9,
  publisherName: "InstaBites",
  date: new Date().toISOString(),
  image: "/assets/DummyData/sandwich.png",
  recipeName: "Lunchbox Stack",
  description: "A stacked sandwich ready for your lunchbox.",
  ingredients: [],
  steps: [],
  tags: ["photo", "lunch", "sandwich"],
  rating: 0,
  numberOfRatings: 0,
  averageRating: 0,
  numberOfLikes: 0,
  postType: "image",
  totalTime: "",
  servings: "",
  source: "",
  isPublished: true,
  isDeleted: false,
}
];
